version: 2

updates:

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates
    assignees:
      - "thomaslaurenson"

  - package-ecosystem: docker
    directory: /mysql
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates
    assignees:
      - "thomaslaurenson"

  - package-ecosystem: docker
    directory: /nginx
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates
    assignees:
      - "thomaslaurenson"

  - package-ecosystem: docker
    directory: /php
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates
    assignees:
      - "thomaslaurenson"
